//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace inventoryProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sale
    {
        public int sale_id { get; set; }
        public Nullable<int> product_id { get; set; }
        public Nullable<int> customer_id { get; set; }
        public Nullable<int> store_id { get; set; }
        public Nullable<int> transaction_id { get; set; }
        public Nullable<System.DateTime> sale_date { get; set; }
        public Nullable<int> quantity { get; set; }
        public Nullable<decimal> rate { get; set; }
        public Nullable<decimal> total_price { get; set; }
        public Nullable<decimal> vat { get; set; }
        public Nullable<decimal> discount { get; set; }
        public Nullable<decimal> net_total_price { get; set; }
        public string stock_status { get; set; }
        public Nullable<int> memo_no { get; set; }
        public string coomments { get; set; }
    
        public virtual customer customer { get; set; }
        public virtual transaction_type transaction_type { get; set; }
        public virtual store store { get; set; }
        public virtual transaction_type transaction_type1 { get; set; }
    }
}
