//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace inventoryProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class stock
    {
        public int stock_id { get; set; }
        public Nullable<int> product_id { get; set; }
        public Nullable<int> store_id { get; set; }
        public Nullable<int> transaction_id { get; set; }
        public Nullable<decimal> purchase_price { get; set; }
        public Nullable<decimal> sale_price { get; set; }
        public Nullable<int> quantity { get; set; }
        public string status { get; set; }
    
        public virtual product product { get; set; }
        public virtual store store { get; set; }
        public virtual transaction_type transaction_type { get; set; }
    }
}
